CREATE TABLE IF NOT EXISTS categories (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  amount_cents INTEGER NOT NULL
);
